version: '3.8'

services:
  es-client:
    image: es-client
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production